name: test

on:
    push:
        branches:
            - master
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: erlef/setup-beam@v1
              with:
                  otp-version: "26.0.2"
                  gleam-version: "1.12.0"
                  rebar3-version: "3"
                  # elixir-version: "1.15.4"
            - uses: actions/setup-node@v6
              with:
                  node-version: 22
            - run: gleam deps download
            - run: npm ci
            - run: npm run test
            - run: gleam format --check src test
